<?php

// dev const
	define('DEVELOPPEMENT', 0); // (int) is in dev ?
								// VALUES : 0 => in production
								// VALUES : 1 => in dev
								// VALUES : 2 => in maintenance
	define('DEVELOPPER_EMAIL', ''); // used to send alerts when a error happens
	define('DB_EMAIL', 'my [at] mail [dot] ext'); // DISPLAY when an db error happens

// db const
	// for security reason, change it in offline/db.php

//DNS const
	define('PREFIX_LINK', '/'); // path in URI to access to the system
	define('PREFIX_ABSOLUTE_LINK', 'http://exemple.com/'); // Absolute URI to access to the system
	define('PREFIX_ABSOLUTE_CDN', 'http://exemple.com/cdn/'); // Absolute URI to access to the CDN folder (it can be a subdomain)
	define('PREFIX_ABSOLUTE_TINY_LINK', 'http://exemple.com/'); // Absolute tiny URI to access to the system if you have it (if you haven't it, fill it like PREFIX_ABSOLUTE_LINK)

// Mail const (via SMTP)
	define('HOST_MAIL', ''); // SMTP host to send mails
	define('PORT_MAIL', ''); // SMTP port to send mails
	define('SMTPSECURE_MAIL', ''); // Sets connection prefix. Options are "", "ssl" or "tls"
	define('SMTPAUTH_MAIL', true); // (bool) sets SMTP authentication
	define('USERNAME_MAIL', ''); // Username to SMTP autentification
	define('PASSWORD_MAIL', ''); // Password to SMTP autentification
	define('ACCOUNT_MAIL', ''); // mail of the smtp account
	define('ADMIN_MAIL', ''); // mail of the admin

// Others
	define('DEFAULT_LANGUAGE', 'en');
	define('NUMBER_OF_OBJECT_BY_PAGES', 6);
	define('NUMBER_OF_PAGE_BY_PAGINATION_BY_SIDE', 5); // Number of page in one side of the current page in the paginations
	define('NAME_OF_THE_SYSTEM', 'OpenLibrerian'); // If you change it, change the differents logo (/favicon.ico and in /cdn/img/) too ! (The icons was generated by realfavicongenerator.net)
	define('GOOGLE_SEARCH_INTO_HTTP_ERRORS_PAGE', 1); // (bool) integrate the google search into some http error page